### ISSUE TITLE
Service screen revamped

### ISSUE THREAD

**Issue by johannes-b** [keptn/enhancement-proposals#40]
# Service screen revamped

**Success Criteria:**  The Keptn Bridge provides a holistic view of the services managed by Keptn.

## Motivation

* *Pain*:  Currently, the service screen is reduced to displaying the evaluation result of a service in a particular stage and a link to the executed sequence.
* *Target*: Help the user to find the required information related to specific service deployment. 
* *Driver*: Provide more service-centered information driven by the main use-cases of Keptn.  

## User stories
- As a user, I would like to see the deployments of a service that are currently running in the environment (i.e., the different stages)
- The main use-cases, which are continuous delivery, quality gate, and auto-remediation, are present and drive the usage of this screen. 
- As a user, I would like to see what happened as part of executed remediations on that service.
- As a user, I would like to see my `SLO.yaml` / `remediation.yaml` configured for a particular deployment. 

## Use-cases
* Multiple dev stages that exist in parallel and allow a developer to run tests as part of the development process.
* Multiple production stages - each for a different customer. 
 
## Mockups

⚠️  Disclaimer: These mockups are subject to change. 

This section explains how the changes in the Bridge will help the user to answer his/her service-related questions. 

* *Question 1*:  What is the status of my service in the entire environment, i.e., in the different stages? 
* *new Feature*: A filter component on the environment screen allows selecting the service I'm interested in. For example, I filter on `carts` and get the following view: 

![image](https://user-images.githubusercontent.com/729071/113976105-d2638b00-9840-11eb-8342-c2d6f858a879.png)

* *Question 2*: Now I'm interested in the deployment `0.9.11` in `production-A`> How can I get more information: I click on `carts:0.9.11` (see yellow highlighting)
* This opens the revamped service screen and pre-selects the deployment `0.9.11` that is running in `production-A`: 

![image](https://user-images.githubusercontent.com/729071/113976146-ec9d6900-9840-11eb-9a1e-5cb0216207e7.png)

*This screen shows:* 
* All deployments of this service that are currently running; see list of `0.12.0`, `0.11.1`, `0.10.3`, `0.9.11` in the left panel. 
* Details about the selected deployment, which is `carts:0.9.11`. The details include:
  * Meta-data like: Git commit and labels
  * The stages the deployment went through or is currently deployed in. 
    * If the bubble is filled, the service is currently running in this sage. Besides, the icon for the deployment URL is displayed (square with arrow) 
    * If the bubble just has a border, a newer version (or another artifact) is currently running in this sage. But you can still take a look at the evaluation result. 
  * The evaluation result for this deployment in this stage; see heatmap and SLI breakdown.

## Work in progress / Open questions

This section contains open questions that need to be refined: 

* How to cover the remediation use-case? Show list of running/executed remediation like: 
![image](https://user-images.githubusercontent.com/729071/113862095-443bc600-97a8-11eb-94b5-6632e376ffee.png)

* How to deal with the quality-gates-only use-case?

**Comment by johannes-b** [comment]
**Breakdown of Value Increments in Dev Epics:**

**Comment by johannes-b** [comment]
## keptn/keptn: Derive the list of deployments that are currently running for a service

The revamped service screen has to answer the question: *Which deployments are currently running for service xyz?*

*For example*: As a user, I open the service screen and select the service *carts*. Then I can see that 3 deployments are actively running which are distributed across the stages of my project. 
- carts:0.11.1 with commit `c123ab9` runs in: `dev`
- carts:0.10.1 with commit `82341b` runs in: `staging`
- carts:0.9.5 with commit `98ab123` runs in: `pre-production`, `production`

**Task:**
- Implement the logic to derive the list of currently deployed services
- Assumption, a delivery (delivery-direct) sequence is responsible for deploying a service
- (Interim solution to show the result/behavior) Display the list of deployments in the "service tile"

![image](https://user-images.githubusercontent.com/729071/112595810-3a5eae00-8e0b-11eb-8a4c-1c6eaec509dc.png)

**Definition of Done**
- [ ] The service tile is telling me which deployments are running in which stage.

**Comment by johannes-b** [comment]
## keptn/keptn: Research: Service screen revamped for improving UX

To derive a great UX on the service screen, the current mockup (see below) has to be refined with the following main questions in mind: 

* [ ] As a user, I would like to see the deployments of a service that are currently deployed in my stages.
* The main use-cases, which are continuous delivery, quality gate, and auto-remediation, are present and drive the usage of this screen.
  * [ ] Can I get the deployment URLs?
  * [ ] What is the quality gate (evaluation) result of deployment `xyz` in stage `abc`? 
  * [ ] Can I see which remediation happened on a deployment?
* [ ] I would like to see all labels for a particular deployment since they provide context information and supporting links.
* [ ] I would like to see the SLO.yaml / remediation.yaml configured for a service (deployment of a service).
* (more relevant questions may arise when working on the mockup)

**Task:**
- Use the mockup (wireframe) - as implemented in a pptx - to design the service screen.
- If the mockup is solid, derive components that can be implemented independently

**Definition of Done:**
- [ ] The mockup(s) provide a good understanding of the look-and-feel of this screen.
- [ ] Concrete components are derived and broken down into sub-issues.

**Mockup**

![image](https://user-images.githubusercontent.com/729071/112599452-3c773b80-8e10-11eb-8b3d-11e9028cfd14.png)

**Comment by johannes-b** [comment]
## keptn/keptn: Filter mechanism on Environment Screen

**User story:** As a user, I would like to see the deployments of a service that are currently running in the environment (i.e., the different stages)

The environment screen provides this information, but this is difficult to grasp when many services are managed in this project. 

**Improvement:** Add a filter component to the environment screen that allows filtering for *Services*: 
* Filter allows multi-selection:
![image](https://user-images.githubusercontent.com/729071/114374215-b08d3f80-9b83-11eb-94c9-6cddd855f58e.png)
* Filter is added on top: 
![image](https://user-images.githubusercontent.com/729071/113976105-d2638b00-9840-11eb-8342-c2d6f858a879.png)

**Definition of Done:**
* [ ] Depending on the service(s) selected by the filter, the view is reduced to the list of services. This includes: 
  - [ ] Information in the stage tiles
  - [ ] Details in the right component

**Comment by johannes-b** [comment]
## keptn/keptn: Click on deployment opens Service screen

**User story:** As a user, I would like to get to the details of a service when clicking the deployment in a stage. Example: When clicking `carts:0.9.11`, the service screen opens with the `carts:0.9.11` pre-selected. 

![image](https://user-images.githubusercontent.com/729071/114375058-96079600-9b84-11eb-92b9-51d8839fa8d8.png)

--> click opens:

![image](https://user-images.githubusercontent.com/729071/113976146-ec9d6900-9840-11eb-9a1e-5cb0216207e7.png)

**Definition of Done:**
- [ ] From the environment screen, I can navigate to a specific deployment by clicking on it.

**Comment by johannes-b** [comment]
## keptn/keptn: Remediation
